### ISSUE TITLE
Video player is too big

### ISSUE THREAD

**Issue by Mennaruuk** [ytmous/ytmous#12]
Unfortunately, unless I go fullscreen, the video player is too big to see completely. Zooming out doesn't help. I have to scroll to find change volume or seek.
![image](https://user-images.githubusercontent.com/52135169/131198412-3540ce0c-32d5-41e6-aa13-728f47675dcf.png)

Example of video that fits:
![image](https://user-images.githubusercontent.com/52135169/131198486-279d123a-bdb0-49bf-be11-7837e1ba47e4.png)

**Comment by Yonle** [comment]
@Mennaruuk Well yeah. By the way the player itself is designed for mobile device. I'm gonna fix that later. PR is welcome

**Comment by Yonle** [comment]
Hi. Sory for the late update.
This bug has been fixed in `nightly` build and therefore can try the experimental watch page. See https://ytmous-nightly.herokuapp.com

**Comment by Mennaruuk** [comment]
Thank you so much! I really appreciate this. I like the new simplicity. Heck, I can run it without JavaScript!! I hope you have a great rest of 2022!!

**Comment by Yonle** [comment]
I may close this issue after merging nightly to master.

**Comment by Yonle** [comment]
Hello 2023.
Appearently, `nightly` branch is still unstable ¯\_ (ツ) _/¯

**Comment by Yonle** [comment]
Merged now. Have a good day :)
