### ISSUE TITLE
Error: Status code 410

### ISSUE THREAD

**Issue by Th3Us3r** [ytmous/ytmous#15]
Sometimes (randomly), when I click on a video, it just says `ytdl Error` then `Error: Status code: 410`. Is there anything causing this?

> here's how it looks:
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/79815764/149610592-5b16c27e-ae8c-4219-bfea-9363f66bedc0.png">

**Comment by Yonle** [comment]
This can be caused by ytdl issue, nor being ratelimited by youtube. You may do this step:

## If you host your own ytmous server
- Update ytdl
- Use proxy / VPN

## If you're using some mirrors
- Change to other mirror
- Consult to the mirror owner

**Comment by iop3** [comment]
stale ?

**Comment by Yonle** [comment]
> stale ?

Nope, as it's somewhat applies to ytdl itself.

**Comment by iop3** [comment]
lol ok

**Comment by Yonle** [comment]
Mirror specific. Closing
