### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by iop3** [ytmous/ytmous#17]
https://ytmous.herokuapp.com/ gives 

<img width="681" alt="image" src="https://user-images.githubusercontent.com/79815764/170805089-9a916bee-f260-4e3c-acf3-419bbdab995a.png">

**Comment by Yonle** [comment]
@iop3 That's how heroku works.
If the project hour reaches to 730 hours, the project will stop and will run again in the next week. 

In meanwhile, You could try other mirror too

**Comment by Yonle** [comment]
@Yonle You may also check #1 for alternative mirrors

**Comment by iop3** [comment]
Ok, thanks for the info.
