### ISSUE TITLE
Are you still gonna add those features? (comments,dislike,etc?)

### ISSUE THREAD

**Issue by Chat-Globally-Media** [ytmous/ytmous#18]
Are you still gonna add those features? (comments,dislike,etc?)

**Comment by Yonle** [comment]
You may also check the `TODO.md` file.

**Comment by Yonle** [comment]
And turns out i implemented 2 features that i listed above in 2023.

**Comment by Chat-Globally-Media** [comment]
> And turns out i implemented 2 features that i listed above in 2023.

Wow i like the new updates you added especially the quality feature which is my fav :) i also fiound a what i think to be **Bug** when being on the video page when scrolling the video info (views, channel, description,etc) scroll up into the video player.

**Comment by Yonle** [comment]
> > And turns out i implemented 2 features that i listed above in 2023.
> 
> Wow i like the new updates you added especially the quality feature which is my fav :) i also fiound a what i think to be **Bug** when being on the video page when scrolling up the video info (views, channel, description,etc) scroll up into the video player.

It was intentioned.

**Comment by Yonle** [comment]
Comments is now there.

**Comment by Chat-Globally-Media** [comment]
WOW! this looks perfect!! i have one more question where do you get/ where can i find the code documentation of the code you put in html that for example (shows sub count, shows author name,etc) which looks like this: <% example,example1 %>

**Comment by Yonle** [comment]
https://github.com/ytmous/ytmous/blob/master/views/watch.ejs#L131-L140

In ytdl-core, You are expected to check the `info` by your own. Could be done simply by `console.log(await ytdl.getInfo(....))`

> EDIT: (i found a bug on the search page when you try to click on a video in the "Latest From user" it just redirects you to /w/ with no video id")

Does not seems reproduceable for me. This may happend with Short videos. Will watch that out.

**Comment by Yonle** [comment]
> EDIT: (i found a bug on the search page when you try to click on a video in the "Latest From user" it just redirects you to /w/ with no video id")

Bug spotted and has been fixed.
