### ISSUE TITLE
ytdl: Invalid regular expression: missing /

### ISSUE THREAD

**Issue by billys41** [ytmous/ytmous#19]
ytdl Error

SyntaxError: Invalid regular expression: missing /

**Comment by Yonle** [comment]
This is ytdl-core bug. See https://github.com/fent/node-ytdl-core/issues/1131 for more information.

In meantime, please downgrade ytdl-core to `4.10.0` by executing `npm install ytdl-core@4.10.0`.

**Comment by billys41** [comment]
do i have to do anything

**Comment by Yonle** [comment]
https://yt-mous.herokuapp.com this mirror should work.

**Comment by billys41** [comment]
idk how to modify my instance on heroku to do the downgrade

**Comment by Yonle** [comment]
> idk how to modify my instance on heroku to do the downgrade 

You can fork this repo then modify package.json

**Comment by billys41** [comment]
I just re deployed this repo making no changes and it worked
