### ISSUE TITLE
to many request

### ISSUE THREAD

**Issue by funtww** [ytmous/ytmous#28]
This project has received too many requests, please try again later.
this is issue that needs to be fixed!!!

**Comment by funtww** [comment]
> This happens because ytmous.glitch.me reaches ratelimit for a number of requests, and has nothing to do with this project.
> 
> Change mirror or try self host.

yes i know this but there is no way i request 4000 requests

**Comment by Yonle** [comment]
> > This happens because ytmous.glitch.me reaches ratelimit for a number of requests, and has nothing to do with this project.
> > 
> > Change mirror or try self host.
> 
> yes i know this but there is no way i request 4000 requests 

As i said before. The project **was ratelimited** just for a while.

This was expected for glitch.com free user, And again, Has nothing to do with this project.

You could wait for a hour so the ratelimit gone.

**Comment by funtww** [comment]
> > > This happens because ytmous.glitch.me reaches ratelimit for a number of requests, and has nothing to do with this project.
> > > Change mirror or try self host.
> > 
> > 
> > yes i know this but there is no way i request 4000 requests
> 
> As i said before. The project **was ratelimited** just for a while.
> 
> This was expected for glitch.com free user, And again, Has nothing to do with this project.
> 
> You could wait for a hour so the ratelimit gone.

thank you
