### ISSUE TITLE
 ytsr Error  TypeError: filterWrapper is not iterable

### ISSUE THREAD

**Issue by billys41** [ytmous/ytmous#32]
ytsr Error

TypeError: filterWrapper is not iterable

**Comment by Yonle** [comment]
The mirror that you use is using older version of ytmous, and therefore i will no longer support it.

If you are the server owner:
- Update ytmous by `git pull`-ing then `npm install`.
- Or just upgrade `ytsr` by running `npm install ytsr@latest` if you still want to use older version.
