### ISSUE TITLE
Can't embed

### ISSUE THREAD

**Issue by Brandon421-ops** [ytmous/ytmous#36]
I can't embed it into a html or I can't use my about:blank cloaker I made to hide it from my history plz fix this. The old ytmous you can embed it but this new one you can't

**Comment by Yonle** [comment]
> embed it into a html or I can't use my about:blank cloaker

You should never supposed to do that especially doing so in someone elses server.

**Comment by Yonle** [comment]
Todo: Add incognito.html for this purpose.
