### ISSUE TITLE
Support for playing Live video on browser

### ISSUE THREAD

**Issue by Yonle** [ytmous/ytmous#6]

**Comment by italodeandra** [comment]
Hey, I came across your project and I'm willing to help you on this issue here. Did you do any research for making live videos also work through the anonymous proxy?

**Comment by Yonle** [comment]
Currently, We're using `m3u8stream` to convert and stream / proxy these m3u8 / dash videos to client.

**Comment by italodeandra** [comment]
Do you know why the live stream don't work?

**Comment by Yonle** [comment]
Becayse the browser did not want to play an live mpegts stream.

**Comment by Yonle** [comment]
Now that i may gonna start experimenting on proxying those chunks.

**Comment by Yonle** [comment]
Implemented & Deployed at https://ytmous.yonle.repl.co

Known Issue: Chrome browser may did not want to stream the livestream
